// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type DeviceTag struct {
	ID         int64
	DeviceName string
	DeviceType string
	Tag        string
}

type HumidityLog struct {
	ID          int64
	Time        time.Time
	Sensor      string
	Temperature float64
	Humidity    float64
	DewPoint    float64
}

type PowerLog struct {
	ID                int64
	Time              time.Time
	Sensor            string
	TotalStartTime    time.Time
	Total             float64
	Yesterday         float64
	Today             float64
	Period            float64
	Power             float64
	ApparentPower     float64
	ReactivePower     float64
	Factor            float64
	Voltage           float64
	Current           float64
	SensorTemperature float64
}

type SwitchStateLog struct {
	ID          int64
	Time        time.Time
	Sensor      string
	SwitchState string
}
